project:
  type: website

website:
  title: Drake Lab
  navbar:
    collapse: false
    tools-collapse: false
    search: false
    right:
      - text: About
        href: http://example.com
      - icon: github
        href: http://github.com

brand:
  dark: _brand.yml
  light: _brand-light.yml
  