website:
  title: Drake Lab
  sidebar:
    logo: d-lab-dark.svg
    contents: 
      - blog.qmd
      - section: Projects
        contents:
          - current.qmd
          - past.qmd
      - people.qmd
    tools:
      - href: https://github.com
        icon: github