project:
  type: website

website:
  title: Drake Lab              
  navbar:
    logo: d-lab.svg
    logo-alt: Drake Lab logo
    left: 
      - blog.qmd
    right:
      - projects.qmd
      - people.qmd
    tools:
      - href: https://github.com
        icon: github